AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 125

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/BlockNesting:
  Max: 5

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'Rakefile'

Metrics/ClassLength:
  Max: 350

Metrics/ParameterLists:
  Max: 10

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/EmptyBlock:
  Enabled: false

Lint/SuppressedException:
  AllowComments: true

Gemspec/RequiredRubyVersion:
  Enabled: false
